#!/bin/bash

function checkReturnedValue () {
    result=$(($line))

    return $result
}

while read -r line
do
    checkReturnedValue $line

    if ./do_op $line | grep -q "The result of $line is $result"; then
        echo "($line): TEST PASSED"
    else
        echo "($line): TEST NOT PASSED"
        echo "expected: "
        echo "The result of $line is $result"
        echo "GOT: "
        ./do_op $line
    fi
done < configFile
