#!/bin/bash


function checkReturnedValue () {
    result=$(($line))

    echo "expected: $result"
}

if [[ $# < 3 ]]
then
    echo "USAGE: ./exercise6-2 [VAL1] [OPERATOR] [VAL2]"
    exit
fi

value1=$1
value2=$3
operator=$2

checkReturnedValue value1 value2 operator